services:
  - type: web
    name: campusos-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: SUPABASE_URL
        value: mock
      - key: SUPABASE_KEY
        value: mock
      - key: PYTHON_VERSION
        value: 3.11.0
